### ISSUE TITLE
Sand and Clay patches might need re-thinking

### ISSUE THREAD

**Issue by WarttHog** [StoneAgeFactorio/StoneAgeFactorio#11]
I think I agree with #6 that the few piles of sand and clay around the starting location are still a bit problematic:
a) Having just enough resources for your needs, right near where you start feels artificial.  Factorio players are used to being able to explore to find more of any natural resources.
b) If you make two charcoal piles or two grates, you get stuck and need to restart the game.
c) It ties you to the starting area until you have collected them, even if there are no biters in the world.

I recommend brainstorming to see if there's some way to make these resources infinite without getting in the way of later gameplay.  Ideas:

1. Spawn them all over the map using normal generation rules.  I suspect you've considered this and have ruled it out as too intrusive.

2. Same as one, but hide the resources better.  Is it possible to make them completely invisible when an iron axe or higher is equipped?  Sand is already blends in quite well.  If you moved clay to the waters edge (where people might logically think to look for it) and change the graphics, it too could blend in.

2b. At the same time would it be an idea to highlight them more when the right tool it picked?  With the placeholder graphics, seeing sand piles in the desert is pretty much impossible... and also hilarious!  :)  The deconstruction planner trick works but it feels hacky and kind of takes you out of the experience..

3. Here's an idea for sand that might be extendable to clay:  Make it possible to mine boulders but make sure it takes a very, very long time.  AS the user is mining (every few seconds), if they have the right tool, drop sand items on the ground around the boulder.  Might be able to do this with jagged rocks when you have the tool.

Actually this might work well for sticks and vines as well.  You're whacking away at the tree with a big stick.  In reality you're not going to take the whole living tree down, but you might knock things out of the tree.

**Comment by RomkeVdMeulen** [comment]
I can spawn more patches to begin with, that should help some. Also, hopefully at some point I can get a graphics designer to help make more recognizable graphics for them.

I can also widen the area over which they will be spawned, so you're not stuck in one area all the time. However, I also have to consider a deathworld scenario where you can't wonder far without encountering lots of biters that you aren't equiped to handle yet.

Long term, I agree the current mechanics don't work well. I had the idea at some point to spawn a bunch of different resources al over, making the player go on a "treasure hunt" and forcing them to explore, but it turned out to be pretty complex.

I haven't completely rules out spawning the additional resources with normal generation, but like you said: it would intrude on later gameplay unless they are "hidden" somehow. But if they blend in too much, players won't be able to find them easily.

I'm not sure the modding API supports mining a resource without it eventually going down. And in vanilla, their mining hardness is so low that even manually, it takes only a few seconds to take them down.  I'm not sure if that can be modified runtime based on the equiped tool. I'll look into it though.

Overall, a complex problem. When next I have time to work on the mod, I'll try some things out and report back. Any additional ideas for solving the problem within these constraints would also be welcome.

**Comment by RomkeVdMeulen** [comment]
I've fooled around with the autoplace settings for hours and have come up with settings that ensure that patches are placed in the starting area, but only very rarely outside it. It's far from perfect, but it does work better than the manual spawning. Another plus is that a bunch of patches are placed close together in a field, making it easier to find (although sand fields are still impossible to find in the desert but custom graphics should help there).

**Comment by RomkeVdMeulen** [comment]
Having tried a few more map generations, I'm starting to think I might go back to the manual spawning. Sometimes you get huge clay and sand patches further out from the starting area that serve no purpose at that point and can even cover ore patches. And inside the starting area, the randomness of the amount of clay and sand means sometimes you don't even have enough to clear the stage, especially once expensive recipes are added.

**Comment by RomkeVdMeulen** [comment]
I've asked for help with the autoplace settings [on the Factorio mod forum](https://forums.factorio.com/viewtopic.php?f=25&t=62852) but no response. I'm going to go back to manual spawning. I think I'll tweak the implementation though, so the patches are grouped together like they are with automatic spawning. That makes them easier to find and looks better anyway.

**Comment by RomkeVdMeulen** [comment]
Switched back to manual spawning. I made the amounts semi-random, but with a minimum that is enough for expensive recipes (provided you make no mistakes). I grouped the patches together. They spawn in a square area, which you can see if you're looking hard, but I don't think that'll be a problem.

**Comment by RomkeVdMeulen** [comment]
This fix hasn't addressed all of @WarttHog's original problems: the resources are still only spawned in one spot in the starting area, and match pretty closely to the amounts needed for the mod. Any other approach though would have patches intruding on later gameplay, so I think this is the lesser of two evils. If somebody comes up with a better solution I'd be glad to re-open this.
