### ISSUE TITLE
Not enough sand and clay

### ISSUE THREAD

**Issue by DJMcMayhem** [StoneAgeFactorio/StoneAgeFactorio#6]
I ended up getting about 3 piles of both sand and clay, which isn't enough to make a kiln. I ended up needing to use console commands to have enough clay to get to the iron pick stage.

**Comment by RomkeVdMeulen** [comment]
There should be four patches of each spawned, though because they are in random locations they aren't always easy to find. As mentioned: once you have a shovel, the deconstruction planner should highlight them.

I borrowed the current graphics for the patches from vanilla. I'm hoping someone will help me design patches that stand out more in the future.
